source 'https://rubygems.org'

gem 'sinatra',                  '1.4.5'

gem 'capistrano',               '3.2.0'
gem 'capistrano-bundler',       '~> 1.1'
gem 'capistrano-nginx-unicorn', '~> 0.1', group: :development
gem 'capistrano-rvm',           '~> 0.1'
gem 'carrierwave',              '0.10.0'
gem 'dotenv',                   '0.11.1'
gem 'friendly_id',              '5.0.4'
gem 'mysql2',                   '0.3.16'
gem 'pony',                     '1.10'
gem 'rabl',                     '0.10.1'
gem 'rmagick',                  '2.13.2'
gem 'sinatra-activerecord',     '2.0.2'
gem 'sinatra-croon',            '0.2.1'
gem 'sinatra-cross_origin',     '0.3.2'
gem 'sinatra-reloader',         '1.0'
gem 'unicorn',                  '4.8.3'
